In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("data.txt", delimiter=';')

C:\Users\danie\AppData\Local\Temp\ipykernel_58132\2970786460.py:1: DtypeWarning: Columns (1,2,5,6,7,8,9,15,16,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data.txt", delimiter=';')

In [4]:
df.head()

,ZIBZIN,IDAvisAutorisationCheque,FlagImpaye,Montant,DateTransaction,CodeDecision,VerifianceCPT1,VerifianceCPT2,VerifianceCPT3,D2CB,...,TauxImpNb_RB,TauxImpNB_CPM,EcartNumCheq,NbrMagasin3J,DiffDateTr1,DiffDateTr2,DiffDateTr3,CA3TRetMtt,CA3TR,Heure
0,A013010004908126703060931,78643044,0,20,2017-02-01 07:32:14,1,0,0,0,551,...,"37,186667890919111","52,076033757361408",0,1,4,4,4,20,0,27134
1,A013011306908024927155000,78643045,0,20,2017-02-01 07:43:37,1,0,0,0,551,...,"48,844716275908937","52,076033757361408",1,2,"1,7976851851851852",4,4,"28,609999999999999","8,6099999999999994",27817
2,A013010002908283134592527,78643046,0,"57,640000000000001",2017-02-01 07:47:38,1,0,0,0,549,...,"73,118279569892479","52,076033757361408",0,1,4,4,4,"57,640000000000001",0,28058
3,A011010002908105209831316,78643047,0,"54,289999999999999",2017-02-01 07:48:48,0,1,1,1,267,...,"110,05692599620494","53,554233554497365",0,1,4,4,4,"54,289999999999999",0,28128
4,A013010041908000125652029,78643048,0,"26,899999999999999",2017-02-01 08:13:27,1,0,0,0,549,...,"45,36831264567185","52,076033757361408",1,1,"1,9971064814814814",4,4,"59,149999999999999","32,25",29607

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4646774 entries, 0 to 4646773
Data columns (total 23 columns):
 #   Column                    Dtype
---  ------                    -----
 0   ZIBZIN                    object
 1   IDAvisAutorisationCheque  object
 2   FlagImpaye                object
 3   Montant                   object
 4   DateTransaction           object
 5   CodeDecision              object
 6   VerifianceCPT1            object
 7   VerifianceCPT2            object
 8   VerifianceCPT3            object
 9   D2CB                      object
 10  ScoringFP1                object
 11  ScoringFP2                object
 12  ScoringFP3                object
 13  TauxImpNb_RB              object
 14  TauxImpNB_CPM             object
 15  EcartNumCheq              object
 16  NbrMagasin3J              object
 17  DiffDateTr1               object
 18  DiffDateTr2               object
 19  DiffDateTr3               object
 20  CA3TRetMtt                object
 21  CA3TR                     object
 22  Heure                     object
dtypes: object(23)
memory usage: 815.4+ MB

In [6]:
df.describe()

,ZIBZIN,IDAvisAutorisationCheque,FlagImpaye,Montant,DateTransaction,CodeDecision,VerifianceCPT1,VerifianceCPT2,VerifianceCPT3,D2CB,...,TauxImpNb_RB,TauxImpNB_CPM,EcartNumCheq,NbrMagasin3J,DiffDateTr1,DiffDateTr2,DiffDateTr3,CA3TRetMtt,CA3TR,Heure
count,4646774,4646774,4646774,4646774,4646774,4646774,4646774,4646774,4646774,4646774,...,4646774,4646774,4646774,4646774,4646774,4646774,4646774,4646774,4646774,4646774
unique,1280127,3831106,5,42864,3097882,10,22,34,43,1103,...,663,82,15585,10,154511,51510,12665,67973,35316,71497
top,A075000041908023367242120,80598968,0,30,2017-03-04 17:18:31,0,0,0,0,1,...,"45,36831264567185","52,076033757361408",0,1,4,4,4,30,0,40646
freq,217,2,4584151,37028,14,3483828,3593113,3593113,3593113,936673,...,202994,445066,4040408,4446255,3162537,3605264,3672048,32497,4068163,207

#### Traitement de la variable cible

In [8]:
print(df['FlagImpaye'].unique())

[0 1 '0' '1' 'FlagImpaye']

In [11]:
# Nettoyage de la colonne 'FlagImpaye' en remplaçant les mauvaises valeurs
df['FlagImpaye'] = df['FlagImpaye'].replace({'FlagImpaye': None, '0': 0, '1': 1})

# Remplacement des NaN par 0 (ou 1 selon votre logique) pour gérer les valeurs manquantes
df['FlagImpaye'].fillna(0, inplace=True)

# Conversion de la colonne en entier
df['FlagImpaye'] = df['FlagImpaye'].astype('int')

C:\Users\danie\AppData\Local\Temp\ipykernel_58132\3661874117.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['FlagImpaye'].fillna(0, inplace=True)

In [12]:
# Vérification après nettoyage
print(df['FlagImpaye'].unique())

[0 1]

In [13]:
# vérifier valeurs manquantes
print(df.isnull().sum())

ZIBZIN                      0
IDAvisAutorisationCheque    0
FlagImpaye                  0
Montant                     0
DateTransaction             0
CodeDecision                0
VerifianceCPT1              0
VerifianceCPT2              0
VerifianceCPT3              0
D2CB                        0
ScoringFP1                  0
ScoringFP2                  0
ScoringFP3                  0
TauxImpNb_RB                0
TauxImpNB_CPM               0
EcartNumCheq                0
NbrMagasin3J                0
DiffDateTr1                 0
DiffDateTr2                 0
DiffDateTr3                 0
CA3TRetMtt                  0
CA3TR                       0
Heure                       0
dtype: int64

#### Train / Test

In [16]:
# Séparation des données en ensembles d'entraînement et de test
train_data = df[(df['DateTransaction'] >= '2017-02-01') & (df['DateTransaction'] <= '2017-08-31')]
test_data = df[(df['DateTransaction'] >= '2017-09-01') & (df['DateTransaction'] <= '2017-11-30')]

In [17]:
# Encodage de la variable 'CodeDecision'
df['CodeDecision'] = df['CodeDecision'].astype('category').cat.codes

In [19]:
print(train_data.columns)

Index(['ZIBZIN', 'IDAvisAutorisationCheque', 'FlagImpaye', 'Montant',
       'DateTransaction', 'CodeDecision', 'VerifianceCPT1', 'VerifianceCPT2',
       'VerifianceCPT3', 'D2CB', 'ScoringFP1', 'ScoringFP2', 'ScoringFP3',
       'TauxImpNb_RB', 'TauxImpNB_CPM', 'EcartNumCheq', 'NbrMagasin3J',
       'DiffDateTr1', 'DiffDateTr2', 'DiffDateTr3', 'CA3TRetMtt', 'CA3TR',
       'Heure'],
      dtype='object')

In [25]:
# Séparation de X et y
X_train = train_data.drop(columns=['FlagImpaye', 'DateTransaction', 'IDAvisAutorisationCheque', 'ZIBZIN'])
y_train = train_data['FlagImpaye']

# Vérification des types
print(X_train.dtypes)

Montant           object
CodeDecision      object
VerifianceCPT1    object
VerifianceCPT2    object
VerifianceCPT3    object
D2CB              object
ScoringFP1        object
ScoringFP2        object
ScoringFP3        object
TauxImpNb_RB      object
TauxImpNB_CPM     object
EcartNumCheq      object
NbrMagasin3J      object
DiffDateTr1       object
DiffDateTr2       object
DiffDateTr3       object
CA3TRetMtt        object
CA3TR             object
Heure             object
dtype: object

In [28]:
from imblearn.over_sampling import SMOTE

# Remplacer les virgules par des points et convertir en float
X_train = X_train.replace({',': '.'}, regex=True)

# Convertir toutes les colonnes en numériques (erreur sera ignorée pour les colonnes non numériques)
X_train = X_train.apply(pd.to_numeric, errors='coerce')

# Vérification des types après conversion
print(X_train.dtypes)

# Application de SMOTE pour équilibrer les classes
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

Montant           float64
CodeDecision        int64
VerifianceCPT1      int64
VerifianceCPT2      int64
VerifianceCPT3      int64
D2CB                int64
ScoringFP1        float64
ScoringFP2        float64
ScoringFP3        float64
TauxImpNb_RB      float64
TauxImpNB_CPM     float64
EcartNumCheq        int64
NbrMagasin3J        int64
DiffDateTr1       float64
DiffDateTr2       float64
DiffDateTr3       float64
CA3TRetMtt        float64
CA3TR             float64
Heure               int64
dtype: object

In [29]:
# Vérification du nombre d'exemples après SMOTE
print(pd.Series(y_train_res).value_counts())

FlagImpaye
0    3865122
1    3865122
Name: count, dtype: int64

In [30]:
# Normalisation/Standardisation des données
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_res_scaled = scaler.fit_transform(X_train_res)

In [31]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# Création et entraînement d'un modèle RandomForest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_res_scaled, y_train_res)

# Prédiction sur les données de test
X_test = test_data.drop(columns=['FlagImpaye', 'DateTransaction', 'IDAvisAutorisAtionCheque', 'ZIBZIN'])
y_test = test_data['FlagImpaye']
X_test_scaled = scaler.transform(X_test)

y_pred = rf_model.predict(X_test_scaled)

# Évaluation du modèle
print(classification_report(y_test, y_pred))

KeyError: "['IDAvisAutorisAtionCheque'] not found in axis"